export const TILES = {
  REQUEST: 'TILES_REQUEST',
  SUCCESS: 'TILES_REQUEST_SUCCESS',
  ERROR: 'TILES_REQUEST_ERROR'
};

export const IMAGES = {
  REQUEST: 'IMAGES_REQUEST',
  SUCCESS: 'IMAGES_SUCCESS',
  ERROR: 'IMAGES_ERROR'
};
